<?php

use Illuminate\Support\Facades\Schema;
use Illuminate\Database\Schema\Blueprint;
use Illuminate\Database\Migrations\Migration;

/**
 * Migration auto-generated by Sequel Pro Laravel Export (1.4.1)
 * @see https://github.com/cviebrock/sequel-pro-laravel-export
 */
class CreateProductDisableKeyTable extends Migration
{
    /**
     * Run the migrations.
     *
     * @return void
     */
    public function up()
    {
        Schema::create('product_disable_key', function (Blueprint $table) {
            $table->increments('id');
            $table->string('shopify_store_id', 191);
            $table->string('product_id', 191);
            $table->string('product_name', 191);
            $table->string('disable_key', 191);
            $table->string('meta_field_id', 191);
            $table->nullableTimestamps();

            

            

        });

        

    }

    /**
     * Reverse the migrations.
     *
     * @return void
     */
    public function down()
    {
        Schema::dropIfExists('product_disable_key');
    }
}
